### ISSUE TITLE
Windows scattered sync read/write incorrectly implemented

### ISSUE THREAD

**Issue by schveiguy** [MartinNowak/io#1]
The caller is expecting read to fill in the buffers sequentially. For a normal file, this may work properly, but for something other than a straight file, it's possible to read less than the requested buffer, but still have more data to read. This will result in garbage data being treated as real data.

Either the read should terminate when it does not read a full buffer (probably the right answer), or the reads should continue on the same buffer until it is full.

Also, a read of 0 bytes should terminate the loop.

**Comment by MartinNowak** [comment]
This applies to the manual compat shim for Window's missing support of scattered file reads.
https://github.com/MartinNowak/io/blob/9f32c594cf6ef7f741adcfac2695e25320c62c68/src/std/io/driver/sync.d#L144-L147
