### ISSUE TITLE
FIXME: Using the imported std.internal.cstring.tempCStringW produces

### ISSUE THREAD

**Issue by wilzbach** [MartinNowak/io#10]
https://github.com/MartinNowak/io/blob/14819fa88016d3f7dcdbe7172c3447e09f5f46a9/src/std/io/internal/string.d#L189

FYI: https://github.com/dlang/phobos/pull/5932 (this will be fixed in 2.078)

**Comment by schveiguy** [comment]
I think this should be fixed now...
https://github.com/MartinNowak/io/commit/6ab5a6381f454e9cf27bde7a7ed3459f5aa05b07
