### ISSUE TITLE
Investigate the viability of using `ReadFileScatter` and `WriteFileGather` for Windows scatter read

### ISSUE THREAD

**Issue by schveiguy** [MartinNowak/io#2]
Requirement is that all the buffers are on a page boundary. `WSASend` and `WSARecv` do not have these requirements, so we can probably use those easier on sockets. See more info here: https://en.wikipedia.org/wiki/Vectored_I/O

**Comment by MartinNowak** [comment]
I'm already using WSASend and WSARecv for sockets.
There seems to be no suitable solution for atomic scatter reads/writes of files on Windows. Relying on page boundary buffers would defeat quite some part of the design (usable for circular buffers), though we might look at using ReadFileScatter/WriteFileGather if buffers actually are page bound at runtime.

**Comment by schveiguy** [comment]
It's probably OK to close this. After considering how normal buffering works, I think scatterRead/gatherWrite operations are quite esoteric, and not sure how much use cases there are for them.

I also found a way to use page mapping tricks to avoid having to do it at all (see ring buffer support in iopipe).

**Comment by MartinNowak** [comment]
scattered read/write is useful for some server-side handling, e.g. to compose a HTTP response.
But indeed this should be monitored closely for usefulness.

**Comment by schveiguy** [comment]
The question really is does scatter read/write work more efficiently than doing it manually, e.g. via fiber-based io
