### ISSUE TITLE
Build failure, dmd 2.088: cast from int to void* not allowed in safe code

### ISSUE THREAD

**Issue by jondegenhardt** [MartinNowak/io#27]
I have started seeing `io` package (v0.2.2) build failures when building [jondegenhardt/dcat-perf](https://github.com/jondegenhardt/dcat-perf). Builds are failing with an error in `driver/package.d`. The error occurs starting with DMD 2.088 / LDC 1.18.0.  I suspect the build failure is a result of [DMD PR #10056](https://github.com/dlang/dmd/pull/10056). The build error is:
```
$ dub build --compiler=ldc2
Performing "debug" build using ldc2 for x86_64.
io 0.2.2: building configuration "library"...
../../../../.dub/packages/io-0.2.2/io/src/std/io/driver/package.d(51,25): Error: cast from int to void* not allowed in safe code
../../../../.dub/packages/io-0.2.2/io/src/std/io/driver/package.d(95,27): Error: cast from int to void* not allowed in safe code
```

There are additional errors, but I suspect that they are a consequence of the initial errors. Compilation with DMD 2.087 / LDC 1.17.0 is fine.

The full build error log can be seen here:  [https://travis-ci.com/jondegenhardt/dcat-perf/builds/134325392](https://travis-ci.com/jondegenhardt/dcat-perf/builds/134325392). Look at the log of any of the failed builds.

**Comment by schveiguy** [comment]
I'll take a look tomorrow. Running into the same issue.

**Comment by schveiguy** [comment]
@jondegenhardt I think this is fixed in master. When I dub add-local io to my repo with my latest changes, it works. Probably just needs a release. I'll tag, let me know if it helps.

**Comment by jondegenhardt** [comment]
Thanks for looking at this Steve. I was wondering if your recent changes would fix it.  I'll try it after you tag it. I'm pulling the `io` package through `iopipe`. If I understand, the `iopipe` dependency will automatically pull a new patch release, so a tag like `v0.2.3` should get it.

Separate thing, but the reason it'll work is because the cast was moved outside of the `@safe:` section, right? Anyway, this case made me wonder what the appropriate @safe mechanism would be. This cast involved, `cast(void*)-1`, is a standard 'C' idiom.

**Comment by schveiguy** [comment]
heh, I just checked and it didn't get updated to code.dlang.org. But I realized I forgot the v. So that should be fixed. Hopefully updates soon.

**Comment by jondegenhardt** [comment]
A mixed bag. DMD 2.088.1 now works with `io-0.2.3`. However, DMD 2.089.0 fails to compile. Looks related to the recent changes to shared/atomics (see the change log and this forum thread: https://forum.dlang.org/thread/qpml3c$up8$1@digitalmars.com).

Very oddly, the LDC 1.18.0 build segment faults when running command line tests. (Run against the built executable.) This is very odd in that LDC 1.18.0 is based on DMD 2.088.1.

I'll take a closer look and let you know what I find. Not sure I'll get to it tomorrow, but will update here when I do.

The build logs are available here: [travis-ci: dcat-perf](https://travis-ci.com/jondegenhardt/dcat-perf/builds/135206605)
- The new dmd-2.089.0 failure: [build 3](https://travis-ci.com/jondegenhardt/dcat-perf/jobs/253510552)
- The ldc-1.18.0 build segment fault: [build 6](https://travis-ci.com/jondegenhardt/dcat-perf/jobs/253510555)

**Comment by schveiguy** [comment]
Hm... reading that thread, especially since we do almost exactly the same thing here: https://github.com/MartinNowak/io/blob/2147802a9bca0dcf82293303f407dd3e253691e9/src/std/io/driver/package.d#L243, I think we probably need to wait for that bug to be fixed and address the "correct" way to do things when 2.089.1 is out. Keep me informed, I'm pretty disconnected from the forums these days.

I don't know about the segfault for LDC that doesn't fail when you use DMD, we may need to report that to LDC. I don't generally use LDC for my projects.

**Comment by jondegenhardt** [comment]
Sounds good. I'll see if I can narrow down the LDC case a bit and report it.

@kinke FYI on possible LDC issue. See my note two comments back. Might be a day or two, but I'll be trying to narrow this further.

**Comment by PetarKirov** [comment]
Guys, consider adding this project to the project tester after you get it green with dmd nightly. It looks like we're missing some test coverage and adding `io` to the list will not only ensure its build stays green with new compiler releases, but also prevent such problems from affecting other projects.

**Comment by schveiguy** [comment]
@PetarKirov yes, will do.

**Comment by schveiguy** [comment]
@bioinfornatics Looks like you hit this same issue with LDC.

@jondegenhardt see issue he filed: ldc-developers/ldc#3219

**Comment by kinke** [comment]
Wrt. the 'LDC issue', somebody please test https://github.com/MartinNowak/io/pull/30, as I haven't, but am pretty sure this is the culprit, and only worked accidentally for `cas()` implementations reinterpret-casting the value to be stored to the destination type (=> not offsetting class to interface pointer), which is more likely actually a DMD issue if it still persists with 2.089.

**Comment by jondegenhardt** [comment]
@schveiguy Looks like the LDC issue is fixed, right? If so, if you tag another version of `io` I'll kick off my CI tests. That'll should close this issue. It'll also have the effect of checking a number of LDC builds.

**Comment by schveiguy** [comment]
OK tagged, @jondegenhardt, now have to just wait for dub to notice.

**Comment by jondegenhardt** [comment]
[jondegenhardt/dcat-perf Travis-CI](https://travis-ci.com/jondegenhardt/dcat-perf/builds/135394458) done. Results as expected. ldc-1.18.0 now passes. dmd-2.089.0 / ldc-1.19.0-beta1 fail on the shared/atomics issue.

**Comment by schveiguy** [comment]
OK, so I'll close this, and open an issue for 2.089.0, as this one as originally reported is fixed.

**Comment by jondegenhardt** [comment]
Hi @schveiguy - I've lost track - What's the status of this? Are we still waiting for something to be fixed in shared atomics on Phobos?

I ask because [jondegenhardt/dcat-perf CI](https://travis-ci.com/jondegenhardt/dcat-perf) builds continue to fail (weekly) for latest dmd and ldc compilers. Same failure on each. E.g.:
```
DMD64 D Compiler v2.090.1
...
Fetching iopipe 0.1.7 (getting selected version)...
Fetching io 0.2.4 (getting selected version)...
...
../../../.dub/packages/io-0.2.4/io/src/std/io/driver/package.d(243,12): Error: template core.atomic.cas cannot deduce function from argument types !()(shared(Driver)*, typeof(null), shared(Driver)), candidates are:
```
This repo is not especially important, so it doesn't matter so much if it fails. But, this strikes me as an important issue, I'm surprised it hasn't been fixed. Or, maybe it has, but I'm just not pulling the correct versions of `iopipe` and `io`.

**Comment by schveiguy** [comment]
I will try to get the workaround in.
