### ISSUE TITLE
prinf with string interpolation 

### ISSUE THREAD

**Issue by bubnenkoff** [MartinNowak/io#4]
I would like to have `printf` function with support of string interpolation (I am not sure that it's named so). All languages have it. Something like:
string name = "Mike";
int age = 20;
`printf("Hello, {0}, your age is {1}", name, age);`

**Comment by schveiguy** [comment]
I don't think this is appropriate for such a library. My understanding is that this library is going to provide the basic building blocks (without buffering) that can be used by higher-level libraries to build more complex structures.

In other words, this just unifies the capabilities of the OS into a very simple D-based interface, to be used in generic code. `printf` functionality is necessarily going to require buffering to make any sense.

**Comment by bubnenkoff** [comment]
Do you plan make replacement of std.stdio?

**Comment by schveiguy** [comment]
I don't speak for @MartinNowak, as this is his library, but my understanding from the library and our discussions on the D forums is that this is supposed to be the foundation of io for any D library that needs it. From the front page: "Implementation of thin OS-independent IO abstractions."

**Comment by schveiguy** [comment]
I'm going to close this, as printf needs buffering, and this should be done with a higher level library.
